---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rsrdev/flagify.rsrdev.com
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/src $DEPLOYPATH/database $DEPLOYPATH/bin
    - /bin/cp index.php $DEPLOYPATH/index.php
    - /bin/cp autoload.php $DEPLOYPATH/autoload.php
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
    - /bin/cp .env.example $DEPLOYPATH/.env.example
    - /bin/cp README.md $DEPLOYPATH/README.md
    - /bin/cp openapi.yaml $DEPLOYPATH/openapi.yaml
    - /bin/cp -R src $DEPLOYPATH/
    - /bin/cp -R database $DEPLOYPATH/
    - /bin/cp -R bin $DEPLOYPATH/
